Small fixes, again

diff --git a/.config/eww/mybar/scripts/media_info b/.config/eww/mybar/scripts/media_info
--- a/.config/eww/mybar/scripts/media_info
+++ b/.config/eww/mybar/scripts/media_info
@@ -6,7 +6,7 @@ select_player () {
 	playingplayer=""
 	coverplayer=""
 	totalplayer=""
-	playerctl -l | while read -r player;
+	playerctl -l 2> /dev/null | while read -r player;
 	do
 		art=`playerctl --player="$player" metadata mpris:artUrl 2> /dev/null`
 		status=`playerctl --player="$player" status 2> /dev/null`
@@ -31,9 +31,16 @@ update_cover () {
 		cp "`echo $newimg | sed 's/file:\/\///g'`" "$imgdir/currmedia.png"
 		echo "Image is a file, succesfully coppied"
 	else
-		curl "$newimg" -o "/tmp/currmedia.png" -s
-		convert "/tmp/currmedia.png" -resize 300x300\! "$imgdir/currmedia.png"
-		echo "Image is an url, succesfully downloaded"
+		echo "Image is an url, trying to download..."
+		curl "$newimg" -o "/tmp/currmedia.png" -s --max-time 5
+		if [[ $? -eq 0 ]]
+		then
+			convert "/tmp/currmedia.png" -resize 300x300\! "$imgdir/currmedia.png"
+			echo "Image succesfully downloaded"
+		else
+			cp "$imgdir/music.png" "$imgdir/currmedia.png"
+			echo "Failed to download image, using template"
+		fi;
 	fi;
 	$eww update cover="$imgdir/currmedia.png"
 }
@@ -58,11 +65,11 @@ lastimg="none"
 eww="eww -c $HOME/.config/eww/mybar"
 
 while true; do
-	if [[ ! -z `playerctl status` ]]
+	if [[ ! -z `playerctl status 2> /dev/null` ]]
 	then
-		player=`select_player | tail -1`
+		player=`select_player 2> /dev/null | tail -1`
 		status=""
-		status=`playerctl --player="$player" status`
+		status=`playerctl --player="$player" status 2> /dev/null`
 		#echo "Selected $player as player"
 
 		# Update status button
@@ -75,7 +82,7 @@ while true; do
 		
 		# Update title and artist
 		last_title="$title"
-		title=`playerctl --player="$player" metadata xesam:title`
+		title=`playerctl --player="$player" metadata xesam:title 2> /dev/null`
 		[[ -z $title ]] && title="No title"
 		if [[ "$title" != "$last_title" ]]
 		then
@@ -98,7 +105,7 @@ while true; do
 		fi;
 
 		last_artist="$artist"
-		artist=`playerctl --player="$player" metadata xesam:artist`
+		artist=`playerctl --player="$player" metadata xesam:artist 2> /dev/null`
 		[[ -z $artist ]] && artist="No artist"
 		if [[ "$artist" != "$last_artist" ]]
 		then
@@ -120,12 +127,11 @@ while true; do
 		fi;
 
 		# Update length and position
-		position=`playerctl --player="$player" position`
+		position=`playerctl --player="$player" position 2> /dev/null`
 		[[ -z $position ]] && position=0
 		$eww update position="$position"
-		length=`playerctl --player="$player" metadata mpris:length`
-		length=`python -c "print($length/1000000)"`
-		[[ -z $length ]] && length=100
+		length=`playerctl --player="$player" metadata mpris:length 2> /dev/null`
+		[[ -z $length ]] && length=100 || length=`python -c "print($length/1000000)"`
 		$eww update length="$length"
 
 		newimg=`playerctl --player="$player" metadata mpris:artUrl 2> /dev/null\
